# Generated by Django 4.2.2 on 2023-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signup_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
